// webstring by june @ webcatz.neocities.org

// webring settings
webring = {

  // list of sites in the ring
  sites: [
    "https://possiblyaxolotl.com",
    "https://jased.xyz",
    "https://abslimeware.neocities.org",
    "https://rejectconvenience.com",
    "https://linkardonline.com",
    "https://yoylecake420.neocities.org",
    "https://maliceinwonderland.nekoweb.org",
    "https://diffydude.neocities.org",
    "https://it-art.neocities.org",
    "https://crazyroostereye.de",
    "https://gabriel.town",
    "https://avq.neocities.org",
    "https://wetnoodle.neocities.org",
    "https://dogonmoon.carrd.co",
    "https://sergioedup.com",
    "https://oceansandy02.nekoweb.org",
    "https://maniksharma.xyz",
    "https://zziz.nekoweb.org",
    "https://evehibi.nekoweb.org",
    "https://axelotl3001.neocities.org",
    "https://justpattie.neocities.org",
    "https://hunipyon.neocities.org",
    "http://minimos11.net",
    "https://xan.lol",
    "https://sugarfantasies.neocities.org",
    "https://beaus-silly-folder.nekoweb.org",
    "https://yammers1.neocities.org",
    "https://edgyrabbid.space",
    "https://goooby.neocities.org",
    "https://pastel-skies.nekoweb.org",
    "https://wriorango.neocities.org",
    "https://orcassiea.nekoweb.org",
    "https://jello01000101.neocities.org",
    "https://zoranadragon.neocities.org",
    "https://dert-cave.neocities.org",
    "https://thatguyfrankenstein.neocities.org",
    "https://chironup.neocities.org",
    "https://sewerwolfx.neocities.org",
    "https://obscou.pages.dev",
    "https://puppygrass.neocities.org",
    "https://bluechinchompa.com",
    "https://transrats.neocities.org",
    "https://drfred.nekoweb.org",
    "https://alienspaceinvader.neocities.org",
    "https://sleepycircus.neocities.org",
    "https://artielas.neocities.org",
    "https://ed1c24.neocities.org",
    "https://deadon.rip",
    "https://zharlzzz.nekoweb.org",
    "https://futch.nekoweb.org",
    "https://candlelightblog.neocities.org",
    "https://ultrakill.nekoweb.org",
    "https://moths-clubhouse.neocities.org",
    "https://staraero.neocities.org",
    "https://u-u.boo",
    "https://kerchunkle.neocities.org",
    "https://willascool.neocities.org",
    "https://silly-beanz.neocities.org",
    "https://myepicsite424.neocities.org",
    "https://orbital-lizard.com",
    "https://hydromaniac.neocities.org",
    "https://ninepsi.nekoweb.org",
    "https://spoingler.neocities.org",
    "https://viktorious-diem.neocities.org",
    "https://on-bambis-mind.neocities.org",
    "https://ihatetehbsod.neocities.org",
    "https://www.bluestarch.com",
    "https://thealleyway.neocities.org",
    "https://cones.lol",
    "https://boatemhq.neocities.org",
    "https://fr3akz0ne.com",
    "https://cryotato.github.io",
    "https://yoyle.city",
    "https://simplyjason.neocities.org",
    "https://daisysite.neocities.org",
    "https://ultra-01.neocities.org",
    "https://darkmagenta.neocities.org",
    "https://nekoha.moe",
    "https://fwing.pet",
    "https://daisybells.neocities.org",
    "https://starfactory.neocities.org",
    "https://sangria.nekoweb.org",
    "https://kaidoesartzz.nekoweb.org",
    "https://chromix.nekoweb.org",
    "https://liquid-sunshine.neocities.org",
    "https://kimt1nez.neocities.org",
    "https://ieatsocks.neocities.org",
    "https://tamago.nekoweb.org",
    "https://caramelpuddinz.neocities.org",
    "https://thedressedmolerat.github.io",
    "https://zirosi.github.io",
    "https://igor360.neocities.org",
    "https://radioheadfan57.neocities.org",
    "https://fireye.coffee",
    "https://epic1.nekoweb.org",
    "https://op0sit.github.io",
    "https://meraki.nekoweb.org",
    "https://americanachronism.neocities.org",
    "https://nightcoreandcaffeine.neocities.org",
    "https://sodarain.neocities.org",
    "https://kirayueyx.neocities.org",
    "https://ghostk.id",
    "https://ourtube.lol",
    "https://samsolarsystem.neocities.org",
    "https://p3p.neocities.org",
    "https://cossechan.nekoweb.org",
    "https://communistwater.neocities.org",
    "https://rociospecialplace.neocities.org",
    "https://thatsrocky.neocities.org",
    "https://sneerful.neocities.org",
    "https://aa-aa-mic-test.neocities.org",
    "https://plumeslegumes.neocities.org",
    "https://ruitherga.neocities.org",
    "https://www.aviatorlaw.eu",
    "https://pucha1985.neocities.org",
    "https://eyntivemd.neocities.org",
    "https://minnerva.neocities.org",
    "https://verysilly.site",
    "https://thekittyburger.neocities.org",
    "https://sleepys.cafe",
    "https://moonlit.exposed",
    "https://coolthings.neocities.org",
    "https://elijahposttrash.neocities.org",
    "https://poprox.nekoweb.org",
    "https://maxsden.neocities.org",
    "https://gob.nekoweb.org",
    "https://napkinonline.nekoweb.org",
    "https://izzysplanet.neocities.org",
    "https://calijori.nekoweb.org",
    "https://mossyscorner.neocities.org",
    "https://wearefarmersdu.neocities.org",
    "https://hml.nekoweb.org",
    "https://drakedragodungeon.neocities.org",
    "https://gabysworld.neocities.org",
    "https://torquuato.github.io",
    "https://waterlily.nekoweb.org",
    "https://d3adb3atdad.neocities.org",
    "https://possumlark.org",
    "https://sculk.nekoweb.org",
    "https://cefa.moe",
    "https://mailoeckchen.neocities.org",
    "https://radioxra.neocities.org",
    "https://bwnxela.neocities.org",
    "https://galaxy.tonehaven.org",
    "https://thegoobersitexd.neocities.org",
    "https://sweetcherries.neocities.org",
    "https://eclipse-the-feathered-dragon.neocities.org",
    "https://clown-in-space.neocities.org",
    "https://flesh-prism.nekoweb.org",
    "https://lotusmoonstart.neocities.org",
    "https://bumblebug.neocities.org",
    "https://biolent.neocities.org",
    "https://brennan.day",
    "https://stacasdepths.neocities.org",
    "https://thesilliestsitever.net",
    "https://pipi.nekoweb.org",
    "https://starzrqp.neocities.org",
    "https://bensgotapen.com",
    "https://freefreakyvideos.nekoweb.org",
    "https://uchicken.nekoweb.org",
    "https://wren-nest.nekoweb.org",
    "https://lunarnotfound.neocities.org",
    "https://minxie.likesyou.org",
    "https://somestranger8.neocities.org",
    "https://pinniped.neocities.org",
    "https://jayshi.me",
    "https://deyathemuniz.neocities.org",
    "https://n3bula.lol",
    "https://deyathemuniz.neocities.org",
    "https://n3bula.lol",
    "https://vergissmichnicht.nekoweb.org",
    "https://smiheart.neocities.org",
    "https://eriswavereal.neocities.org",
    "https://notforyoubunny.neocities.org",
    "https://yaxro.com",
    "https://if-we-were-villains.nekoweb.org",
  ],

  // html inserted as your widget
  // PREV and NEXT get replaced with neighboring site urls
  widget: `
    <div class="comic-neue-bold" id="sillyring" style="display: inline; text-align: center; width:min-content; gap: 8px">
      <img id="sillyring-image" src="https://silly.possiblyaxolotl.com/tbhspin.gif" /><br>
      <a href="PREV" target="_top">â—„</a>      
      <a href="https://silly.possiblyaxolotl.com" target="_top">sillyring</a>
      <a href="NEXT" target="_top">â–º</a>
    </div>
  `,

  stylesheet: "https://silly.possiblyaxolotl.com/ring/sillystyle.css",

  // html inserted instead of your widget on sites that aren't in the ring
  error: `
    <div class="comic-neue-bold" id="sillyring" style="display: inline; text-align: center; width:min-content; gap: 8px">
      <img id="sillyring-image" src="https://silly.possiblyaxolotl.com/tbhspin.gif" /><br>
      <p>This site isn't part of sillyring yet 3:</p>
    </div>
  `,

};

// code
webring.index = location.href.startsWith("file:") ? 0 : webring.sites.findIndex(url => location.href.startsWith(url));
if (webring.index === -1) document.currentScript.outerHTML = webring.error;
else {
let sheet = document.createElement("link");
sheet.rel = "stylesheet", sheet.href = webring.stylesheet;
document.head.appendChild(sheet);
webring.widget = webring.widget.replace("PREV", webring.sites.at(webring.index - 1));
webring.widget = webring.widget.replace("NEXT", webring.sites[(webring.index + 1) % webring.sites.length]);
document.currentScript.outerHTML = webring.widget;
}
delete webring;

